#!/bin/zsh
DIRECTORY="$HOME/usage"
if [ ! -d "$DIRECTORY" ]; then
  mkdir $DIRECTORY
fi

VERSION="1.0"
EMAIL="your@email.com"

case $1 in
	help)
		echo ""
		echo "Usage - The xorg program usage monitor."
		echo "Version $VERSION"
		echo "----------------------------------------"
		echo "Usage: usage <option>"
		echo "Options:"
		echo "	help - shows this help page"
		echo "	track - track program usage"
		echo "	show - shows recorded program usage"
		echo "	clear - clears recorded usage data"
		echo "	send - email the program usage data"
		echo "----------------------------------------"
		echo ""
		;;
	track)
		cd $DIRECTORY
		while true; do 
			thyme track -o thyme.json; sleep 30s 
		done
		;;
	show)
		cd $DIRECTORY
		thyme show -i thyme.json -w stats > thyme.html
		chromium thyme.html
		;;
	clear)
		cd $DIRECTORY
		rm thyme.json
		rm thyme.html
		;;
	send)
		cd $DIRECTORY
		thyme show -i thyme.json -w stats > thyme.html
		zip -r usage.zip thyme.*
		neomutt -s "USAGE - Computer usage summary for james." -a usage.zip -- $EMAIL < /dev/null
		;;
		
	*)
		echo ""
		echo "Usage - The xorg program usage monitor."
		echo "Version $VERSION"
		echo "----------------------------------------"
		echo "Usage: usage <option>"
		echo "Options:"
		echo "	help - shows this help page"
		echo "	track - track program usage"
		echo "	show - shows recorded program usage"
		echo "	clear - clears recorded usage data"
		echo "	send - email the program usage data"
		echo "----------------------------------------"
		echo ""
		;;
esac
